name: aplicacion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  cupertino_icons: ^1.0.8
  firebase_dynamic_links: ^6.1.5
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  path: ^1.9.1
  firebase_crashlytics: ^4.3.5
  cached_network_image: ^3.4.1
  go_router: ^15.1.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - json/base.json

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png"