// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmzk2h2fAd4Ok7nnjgwSzzxfwzRjbSPMA',
    appId: '1:62474107022:web:beb4b70dbcc18abb3af1df',
    messagingSenderId: '62474107022',
    projectId: 'dylantareas-d92e1',
    authDomain: 'dylantareas-d92e1.firebaseapp.com',
    storageBucket: 'dylantareas-d92e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzsTfCCFzMu-tlrCUUXOI3Fl_9VzeoKGY',
    appId: '1:62474107022:android:f25e502cf1682f9d3af1df',
    messagingSenderId: '62474107022',
    projectId: 'dylantareas-d92e1',
    storageBucket: 'dylantareas-d92e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK_p7ThKcL2xEcJFy2tkD3AEDQcqVgPkg',
    appId: '1:62474107022:ios:b6d6199f943867563af1df',
    messagingSenderId: '62474107022',
    projectId: 'dylantareas-d92e1',
    storageBucket: 'dylantareas-d92e1.firebasestorage.app',
    iosBundleId: 'com.example.aplicacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK_p7ThKcL2xEcJFy2tkD3AEDQcqVgPkg',
    appId: '1:62474107022:ios:b6d6199f943867563af1df',
    messagingSenderId: '62474107022',
    projectId: 'dylantareas-d92e1',
    storageBucket: 'dylantareas-d92e1.firebasestorage.app',
    iosBundleId: 'com.example.aplicacion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmzk2h2fAd4Ok7nnjgwSzzxfwzRjbSPMA',
    appId: '1:62474107022:web:20bc0badaedeaf8f3af1df',
    messagingSenderId: '62474107022',
    projectId: 'dylantareas-d92e1',
    authDomain: 'dylantareas-d92e1.firebaseapp.com',
    storageBucket: 'dylantareas-d92e1.firebasestorage.app',
  );
}
